name: Run for a PR

on:  
  pull_request:
    branches:
      - main

jobs:
  build:
    name: PR Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Build Backend for PR
        id: build-backend
        run: |
            echo "Hello World" 
    


    
