name: Deploy Backend Production to AWS ECS

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test-env

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Hello World
        run: |    
           echo "Hello Keshav"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
